[tool.poetry]
name = "spectral-paths"
version = "0.1.0"
description = "Spectral-path regression with greedy sparse dictionary selection."
authors = ["Milo Coombs <milo.coombs7@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.12,<4.0"
numpy = "<2.4"
numba = ">=0.63.1,<0.64.0"
scikit-learn = ">=1.8.0,<2.0.0"
openml = "^0.15.1"
threadpoolctl = ">=3.5.0,<4.0.0"
ipykernel = "^7.2.0"
xgboost = "^3.2.0"
interpret = "^0.7.8"

[tool.poetry.group.dev.dependencies]
pytest = ">=9.0.2,<10.0.0"
ruff = ">=0.14.11,<0.15.0"
mypy = "^1.19.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.mypy]
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = ["numba", "numba.*"]
ignore_missing_imports = true
follow_imports = "skip"

[tool.ruff]
line-length = 100

[tool.ruff.lint]
select = ["E","W", "F", "I", "B", "C4", "N", "D", "D213"]
ignore = ["D212", "N803", "N806", "B023"]

[tool.ruff.lint.pydocstyle]
convention = "google"
